on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build:
    name: "Build and Publish"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Install Dependencies
        run: sudo apt-get -y install zsync fuse build-essential

      - name: Install VCPKG
        uses: lukka/run-vcpkg@v4
        with:
          setupOnly: true

      - name: Install libtorrent and boost
        run: |
          $VCPKG_ROOT/vcpkg integrate install
          $VCPKG_ROOT/vcpkg install boost:linux-64 
          $VCPKG_ROOT/vcpkg install libtorrent

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake -DGIT_COMMIT=$(git rev-parse --short HEAD) -DBUILD_TIME=$(datetime) ..
          make -j$(nproc)

      - name: Build AppImage
        id: appimage_build
        env:
          VERSION: git rev-parse --short HEAD
        run: |
          cd ..
          mkdir -p appdir/usr/bin ; strip build/MakeAppImageTorrent ; cp build/MakeAppImageTorrent appdir/usr/bin/
          mkdir -p appdir/usr/share/applications ; cp MakeAppImageTorrent.desktop appdir/usr/share/applications/
          mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ 
          cp MakeAppImageTorrent.png appdir/usr/share/icons/hicolor/256x256/apps/MakeAppImageTorrent.png 
          wget -q http://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          export VERSION=$(git rev-parse --short HEAD)
          export UPDATE_INFORMATION="gh-releases-zsync|antony-jr|MakeAppImageTorrent|latest|MakeAppImageTorrent*-x86_64.AppImage.zsync"
          ./linuxdeploy-x86_64.AppImage --appdir appdir
          chmod +x MakeAppImageTorrent*-x86_64.AppImage
          ./MakeAppImageTorrent*-x86_64.AppImage MakeAppImageTorrent*-x86_64.AppImage

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Automatically deployed from Github Actions."
          draft: false
          prerelease: false
      - name: Upload AppImage Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MakeAppImageTorrent-${{steps.appimage_build.env.VERSION}}-x86_64.AppImage
          asset_name: MakeAppImageTorrent-${{steps.appimage_build.env.VERSION}}-x86_64.AppImage
      - name: Upload AppImage Zsync File Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MakeAppImageTorrent-${{steps.appimage_build.env.VERSION}}-x86_64.AppImage.zsync
          asset_name: MakeAppImageTorrent-${{steps.appimage_build.env.VERSION}}-x86_64.AppImage.zsync
      - name: Upload AppImage Torrent File Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MakeAppImageTorrent-${{steps.appimage_build.env.VERSION}}-x86_64.AppImage.torrent
          asset_name: MakeAppImageTorrent-${{steps.appimage_build.env.VERSION}}-x86_64.AppImage.torrent
