on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: "Build and Publish"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: rainlabs-eu/ghaction-cmake-quality@v1  

      - name: Install Dependencies
        run: sudo apt-get -y install zsync fuse build-essential libboost-system libtorrent-rasterbar8 libtorrent-rasterbar-dev

      - name: Build Project
        run: mkdir build
        run: cd build
        run: cmake -DGIT_COMMIT=$(git rev-parse --short HEAD) -DBUILD_TIME=$(datetime) ..
        run: make -j$(nproc)

      - name: Build AppImage
        id: appimage_build
        env:
          VERSION: git rev-parse --short HEAD
        run: cd ..
        run: mkdir -p appdir/usr/bin ; strip build/MakeAppImageTorrent ; cp build/MakeAppImageTorrent appdir/usr/bin/
        run: mkdir -p appdir/usr/share/applications ; cp MakeAppImageTorrent.desktop appdir/usr/share/applications/
        run: mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ 
        run: cp MakeAppImageTorrent.png appdir/usr/share/icons/hicolor/256x256/apps/MakeAppImageTorrent.png 
        run: wget -q http://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        run: chmod +x linuxdeploy-x86_64.AppImage
        run: export VERSION=$(git rev-parse --short HEAD)
        run: export UPDATE_INFORMATION="gh-releases-zsync|antony-jr|MakeAppImageTorrent|latest|MakeAppImageTorrent*-x86_64.AppImage.zsync"
        run: ./linuxdeploy-x86_64.AppImage --appdir appdir
        run: chmod +x MakeAppImageTorrent*-x86_64.AppImage
        run: ./MakeAppImageTorrent*-x86_64.AppImage MakeAppImageTorrent*-x86_64.AppImage

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Automatically deployed from Github Actions."
          draft: false
          prerelease: false
      - name: Upload AppImage Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MakeAppImageTorrent-${{steps.appimage_build.VERSION}}-x86_64.AppImage
          asset_name: MakeAppImageTorrent-${{steps.appimage_build.VERSION}}-x86_64.AppImage
      - name: Upload AppImage Zsync File Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MakeAppImageTorrent-${{steps.appimage_build.VERSION}}-x86_64.AppImage.zsync
          asset_name: MakeAppImageTorrent-${{steps.appimage_build.VERSION}}-x86_64.AppImage.zsync
      - name: Upload AppImage Torrent File Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MakeAppImageTorrent-${{steps.appimage_build.VERSION}}-x86_64.AppImage.torrent
          asset_name: MakeAppImageTorrent-${{steps.appimage_build.VERSION}}-x86_64.AppImage.torrent
